<a href="https://colab.research.google.com/github/2b-pixel/2b-pixel.github.io/blob/main/oct14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

url = "https://raw.githubusercontent.com/yongmeiwang/AI_BigData_CancerBiology/main/Data/gtex_integrin_7_organs.xlsx"
Gtex_integrin = pd.read_excel(url)

Gtex_integrin.head()

,Unnamed: 0,primary_site,ITGA10,ITGAD,ITGAM,ITGA3,ITGBL1,ITGAE,ITGA2,ITGB3,...,ITGA6,ITGA2B,ITGB1,ITGAL,ITGA9,ITGB5,ITGA8,ITGA4,ITGA1,ITGA11
0,GTEX-13QIC-0011-R1a-SM-5O9CJ,Brain,0.5763,-6.5064,2.2573,0.7832,1.0363,4.6035,2.5731,-2.8262,...,2.8562,1.3846,5.8430,1.1316,-0.7108,3.5387,-0.0725,-0.4521,0.2029,-2.8262
1,GTEX-1399S-1726-SM-5L3DI,Lung,4.9137,-3.6259,4.7307,7.1584,1.7702,4.9556,1.9149,2.6067,...,4.2412,4.1211,7.7256,4.4900,2.9281,6.1483,5.1867,2.6185,4.7856,-0.0277
2,GTEX-PWCY-1326-SM-48TCU,Ovary,2.3953,-5.0116,1.4547,4.2593,-0.7346,4.4149,0.2642,1.5216,...,3.6816,1.5465,7.2964,-0.9406,2.7742,5.0414,2.0325,0.7579,2.2573,1.2516
3,GTEX-QXCU-0626-SM-2TC69,Lung,4.0541,-2.3147,4.5053,7.5651,4.1788,4.1772,5.3695,1.8444,...,4.9631,1.9149,7.9947,3.3911,2.8462,6.7683,4.1636,2.7951,5.3284,1.2147
4,GTEX-ZA64-1526-SM-5CVMD,Breast,2.0569,-2.4659,3.3993,3.1311,3.0074,4.4977,-1.7809,2.7139,...,4.7340,0.6332,7.3496,-0.9406,2.5338,6.5696,1.7229,-0.6416,3.1195,1.1050

In [10]:
Gtex_lung_brain.shape

(1440, 29)

In [9]:
Gtex_lung_brain=Gtex_integrin[Gtex_integrin['primary_site'].isin(['Lung','Brain'])]

In [11]:
Gtex_lung_brain['primary_site'].value_counts()

primary_site
Brain    1152
Lung      288
Name: count, dtype: int64

In [13]:
Ovary_Breast=Gtex_integrin[Gtex_integrin['primary_site'].isin(['Ovary','Breast'])]

In [14]:
Ovary_Breast.shape

(267, 29)